version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: blog-minseok-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./data:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3320:3306'
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: blog-minseok-redis
    restart: always
    ports:
      - '6479:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
